// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoGqZCaHeBBlQNOTz90Zh7OQ3V6fw_eOI',
    appId: '1:983110812621:web:4b3fee56d9c33b81fffa84',
    messagingSenderId: '983110812621',
    projectId: 'deb-shiftsync-7984c',
    authDomain: 'deb-shiftsync-7984c.firebaseapp.com',
    storageBucket: 'deb-shiftsync-7984c.firebasestorage.app',
    measurementId: 'G-B8L0W12KHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDdA6dfM-6NJvTnItr1KOcezxSESJK0ak',
    appId: '1:983110812621:android:84ab1df8f2b7f6eafffa84',
    messagingSenderId: '983110812621',
    projectId: 'deb-shiftsync-7984c',
    storageBucket: 'deb-shiftsync-7984c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIK38U-Uv_cVIUjE4nxFqmj-QeraDYxwM',
    appId: '1:983110812621:ios:c5f5e95e46093035fffa84',
    messagingSenderId: '983110812621',
    projectId: 'deb-shiftsync-7984c',
    storageBucket: 'deb-shiftsync-7984c.firebasestorage.app',
    iosBundleId: 'com.shiftcalendar.shiftCalendar',
  );
}
